name: Release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Test
        run: |
          pip install -e .
          python -m unittest discover tests/unit
      - name: Release
        run: |
          version=`python .github/scripts/update_version.py`
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Bump"
          git tag -a v$version -m "Release $version" 
          git push origin master
          git push origin v$version
          gh release create v$version --notes "Release $version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
